### PR TITLE
 Using Bootstrap - Newsweek Clone

### PR DESCRIPTION
**Pull request by jelduran**
Project 7 - Using Bootstrap, part of Microverse curriculum. The goal is building a  Newsweek's Homepage Clone using HTML and Bootstrap Framework.

### CODE REVIEW

**Review by HADDADSOHAIB — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: 

### Hi @jelduran  :+1: 

### your project looks good, but there is some changes that are required before we approved your project.

- A pull request should always have a description that contain details about it
Screenshot from 2020-07-04 01-49-22
please provide a description
- You have inline styles in your HTML file (line 1888), please move all the styles to your css file.
- Where the tablet view ? I think you have the tablet view missing, you move directly from desktop <=> mobile.
original
Screenshot from 2020-07-04 01-56-34
clone
Screenshot from 2020-07-04 01-56-15
So the project need to be fixed, not the show part in the picture.
- the newsletter and subscribe sections are not similar to the original:
clone
Screenshot from 2020-07-04 02-03-59
original
Screenshot from 2020-07-04 02-04-20
This part of the project is very responsive and change a lot, make sure that the clone do the same as the original.
 ### Once done wth tha changes, ask for another code review

**Comment by jelduran** [comment]
Thank you @HADDADSOHAIB TSE for your feedback, I appreciated it a lot.

**Review by HADDADSOHAIB — CHANGES_REQUESTED** [review]
### Status: Change required :recycle: 

### Hi @jelduran :+1: 

### You are most welcomed, you did great with most of the changes, but there is still  some additional ones:
- You did not add a description to your pull request.
Screenshot from 2020-07-04 22-02-10
- subscribe section still need some improvements in the mobile view:
original:
Screenshot from 2020-07-04 22-02-50
clone:
Screenshot from 2020-07-04 22-02-34
- In tablet view, the articles don't take 100% of the width like the original:
original:
Screenshot from 2020-07-04 22-04-41
clone:
Screenshot from 2020-07-04 22-04-53
- the same issue here
clone
Screenshot from 2020-07-04 22-07-22
original
Screenshot from 2020-07-04 22-07-36
### once done with the changes, please ask for another code review

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑

## Hello @jelduran 👋. I am spellbound after seeing your project 🤩. This is mindblowing 🤯. This makes me wonder...were you the original designer of the Newsweek page? 👌👏🧨💪🙌 💯 !

### You gave me a hard time determining which was the clone and which was the original page. This is true mastery 💯! 

But your HTML file contains some errors. This prevented me from approving this project 😩.

image

Please fix the above errors and request another review.

Happy coding 👨‍💻

**Comment by jelduran** [comment]
Thank you @tirthajyoti-ghosh for so nice feedback!

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Approved ✅

## It's a 👍 from me. Go ahead and merge it.

### Best of luck with your capstone project.

#### Happy coding 👨‍💻

**Pull request merged**
